package com.codigomestre.servidor.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 */
@WebService(name = "HelloWorld", targetNamespace = "http://ws.ws.servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorld {

	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://com.codigomestre.servidor.ws/HelloWorld/getHelloWorldMessageRequest", output = "http://com.codigomestre.servidor.ws/HelloWorld/getHelloWorldMessageResponse")
	public String getHelloWorldMessage(
			@WebParam(name = "arg0", partName = "arg0") String arg0);
	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://com.codigomestre.servidor.ws/HelloWorld/getHelloWorldMessageByNameRequest", output = "http://com.codigomestre.servidor.ws/HelloWorld/getHelloWorldMessageByNameResponse")
	public String getMyName(
			@WebParam(name = "nome", partName = "nome") String nome);
}