package com.codigomestre.servidor.ws;


import java.io.File;
import java.util.Properties;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

import org.eclipse.swt.graphics.Resource;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 */
@WebService(name = "ServidorCliente", targetNamespace = "http://ws.ws.servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServidorCliente {

	@WebMethod
	@WebResult(partName = "return")
	@Action(input = "http://com.codigomestre.servidor.ws/ServidorCliente/cadastroRequest", output = "http://com.codigomestre.servidor.ws/ServidorCliente/cadastroResponse")
	public Properties cadastro(
			@WebParam(name = "properties", partName = "properties") Properties properties);

	
}